// assets/components/banner.jsx
'use strict'

const React = require('react')

const NavItem = require('./nav-item')

const sections = [
  'Politics',
  'Opinions',
  'Sports',
  'Local',
  'National',
  'World',
  'Vue',
  'Handlebars'
]

const Banner = props => (
  <nav className='navbar fixed-top navbar-expand navbar-dark bg-dark'>
    {/* <a className='navbar-brand' href='/'>
      Washington Post
    </a> */}
    <button className='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span className='navbar-toggler-icon' />
    </button>
    <div className='collapse navbar-collapse' id='navbarNav'>
      <ul className='navbar-nav'>
        {sections.map(s => <NavItem key={s} label={s} />)}
      </ul>
    </div>
  </nav>
)

module.exports = Banner

// assets/components/banner.vue
<template>
  <nav class="navbar fixed-top navbar-expand navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon" />
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <nav-item v-for="label in sections" :key="label" :label="label" />
      </ul>
    </div>
  </nav>
</template>

<script>
const NavItem = require('./nav-item.vue')

module.exports = {
  components: {
    NavItem
  },
  data: () => ({
    sections: [
      'Politics',
      'Opinions',
      'Sports',
      'Local',
      'National',
      'World',
      'Vue',
      'Handlebars'
    ]
  })
}
</script>
