// assets/components/in-the-news.jsx
'use strict'

const React = require('react')

const Consumer = require('consumer')

const NavItem = require('./nav-item')

class InTheNews extends React.Component {
  constructor (props) {
    super(props)
    this.fetch(`/_content/in-the-news`)
  }

  render () {
    return this.state && this.state.content
      ? (
        <div>
          <hr style={{margin: 0, borderColor: '#000', borderWidth: '4px'}} />
          <ul className='nav'>
            {this.state.content.map(i => <NavItem key={i} label={i} />)}
          </ul>
          <hr style={{margin: 0, borderColor: '#000'}} />
        </div>
      )
      : <div />
  }
}

module.exports = Consumer(InTheNews)

// assets/components/in-the-news.vue
<template>
  <div>
    <hr style="margin: 0; border-color: #000; border-width: 4px" />
    <ul class="nav">
      <nav-item v-for="label in items" :key="label" :label="label" />
    </ul>
    <hr style="margin: 0; border-color: #000" />
  </div>
</template>

<script>
const NavItem = require('./nav-item.vue')

module.exports = {
  components: {
    NavItem
  },
  data () {
    (typeof window !== 'undefined') &&
      window.fetch(`/_content/in-the-news`)
        .then(response => response.json())
        .then(json => {
          this.$set(this, 'items', json.content)
        })

    return {items: []}
  }
}
</script>
