// assets/components/nav-item.vue
<template>
  <li class="nav-item">
    <a :class="classes" :href="computedHref">{{label}}</a>
  </li>
</template>

<script>
module.exports = {
  props: ['label', 'href'],
  data () {
    const computedHref = this.href || `/${this.label.replace(' ', '-').toLowerCase()}`
    const active = (typeof window === 'undefined')
      ? false
      : (() => {
        const location = window.location
        const uri = location.pathname
        return uri ? (new RegExp(`^${computedHref}(\\?|#|$)`)).test(uri) : false
      })()

    return {
      classes: `nav-link${active ? ' active' : ''}`,
      computedHref
    }
  }
}
</script>

// assets/components/nav-item.jsx
'use strict'

const React = require('react')

const Consumer = require('consumer')

class NavItem extends React.Component {
  render () {
    const href = this.props.href || `/${this.props.label.replace(' ', '-').toLowerCase()}`
    const active = this.uri ? (new RegExp(`^${href}(\\?|#|$)`)).test(this.uri) : false
    return (
      <li className={'nav-item' + (active ? ' active' : '')}>
        <a className='nav-link' href={href}>{this.props.label}</a>
      </li>
    )
  }
}

module.exports = Consumer(NavItem)
