// assets/components/wrapper.jsx
'use strict'

const React = require('react')

const Banner = require('./banner')
const Breaking = require('./breaking')
const InTheNews = require('./in-the-news')
const Title = require('./title')

const Wrapper = props => (
  <div>
    <Banner />
    <div style={{margin: '66px 30px 30px'}}>
      <Breaking />
      <Title />
      <InTheNews />
      {props.children}
    </div>
  </div>
)

module.exports = Wrapper

// assets/components/wrapper.vue
<template>
  <div>
    <banner />
    <div style="margin: 66px 30px 30px">
      <breaking />
      <app-title />
      <in-the-news />
      <slot />
    </div>
  </div>
</template>

<script>
const Banner = require('./banner.vue')
const Breaking = require('./breaking.vue')
const InTheNews = require('./in-the-news.vue')
const AppTitle = require('./title.vue')

module.exports = {
  components: {
    Banner,
    Breaking,
    InTheNews,
    AppTitle
  }
}
</script>
