// assets/components/nav-item.vue
<template>
  <li class="nav-item">
    <a :class="classes" :href="computedHref">{{label}}</a>
  </li>
</template>

<script>
module.exports = {
  props: ['label', 'href'],
  data () {
    const computedHref = this.href || `/${this.label.replace(' ', '-').toLowerCase()}`
    const active = (typeof window === 'undefined')
      ? false
      : (() => {
        const location = window.location
        const uri = location.pathname
        return uri ? (new RegExp(`^${computedHref}(\\?|#|$)`)).test(uri) : false
      })()

    return {
      classes: `nav-link${active ? ' active' : ''}`,
      computedHref
    }
  }
}
</script>

// components/nav-item.jsx
'use strict'

const React = require('react')

const NavItem = props => {
  const routePattern = props.uri ? new RegExp(`^${props.href}(\\?|#|$)`) : null
  return (
    <li className={'nav-item' + (routePattern && routePattern.test(props.uri) ? ' active' : '')}>
      <a className='nav-link' href={props.href}>{props.label}</a>
    </li>
  )
}

module.exports = NavItem
