// assets/components/breaking.vue
<template>
  <div v-if="breaking" class="alert alert-secondary alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <strong>Breaking News:</strong> {{breaking}}
  </div>
</template>

<script>
module.exports = {
  data () {
    (typeof window !== 'undefined') &&
      window.fetch(`/_content/breaking-news`)
        .then(response => response.json())
        .then(json => {
          this.$set(this, 'breaking', json.content)
        })

    return {breaking: null}
  }
}
</script>

// renderer/components/breaking.jsx
'use strict'

/* global $ */

const React = require('react')
const Consumer = require('consumer')

class Breaking extends React.Component {
  constructor (props) {
    super(props)
    this.async(props.content || `/_content/404`)
  }

  componentDidMount () {
    $('.alert').alert()
  }

  render () {
    return this.state && this.state.body
      ? (
        <div className='alert alert-secondary alert-dismissible' role='alert'>
          <button type='button' className='close' data-dismiss='alert' aria-label='Close'>
            <span aria-hidden='true'>&times;</span>
          </button>
          <strong>Breaking News:</strong> {this.state.body}
        </div>
      )
      : <div />
  }
}

module.exports = Consumer(Breaking)
