// assets/components/in-the-news.vue
<template>
  <div>
    <hr style="margin: 0; border-color: #000; border-width: 4px" />
    <ul class="nav">
      <nav-item v-for="label in items" :key="label" :label="label" />
    </ul>
    <hr style="margin: 0; border-color: #000" />
  </div>
</template>

<script>
const NavItem = require('./nav-item.vue')

module.exports = {
  components: {
    NavItem
  },
  data () {
    (typeof window !== 'undefined') &&
      window.fetch(`/_content/in-the-news`)
        .then(response => response.json())
        .then(json => {
          this.$set(this, 'items', json.content)
        })

    return {items: []}
  }
}
</script>

// renderer/components/in-the-news.jsx
'use strict'

const React = require('react')

const NavItem = require('./nav-item')

const items = [
  'Hurricane Jose',
  'Irma',
  'Richard Branson'
]

const InTheNews = props => (
  <div>
    <hr style={{margin: 0, borderColor: '#000', borderWidth: '4px'}} />
    <ul className='nav'>
      {items.map(i => <NavItem label={i} />)}
    </ul>
    <hr style={{margin: 0, borderColor: '#000'}} />
  </div>
)

module.exports = InTheNews
